FROM node:20-alpine AS deps
WORKDIR /app

# Install dependencies
COPY package.json pnpm-lock.yaml* ./
RUN corepack enable && corepack prepare pnpm@8.15.4 --activate && pnpm i --frozen-lockfile

# Rebuild the source code only when needed
FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# 声明构建参数
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_SITE_NAME
ARG NEXT_PUBLIC_SITE_DESCRIPTION
ARG NEXT_PUBLIC_AUTHOR_NAME
ARG NEXT_PUBLIC_TWITTER_USERNAME
ARG NEXT_PUBLIC_BAIDU_TONGJI
ARG NEXT_PUBLIC_GOOGLE_ID
ARG NEXT_PUBLIC_SEO_GOOGLE_SITE_VERIFICATION
ARG NEXT_PUBLIC_ADSENSE_GOOGLE_ID
ARG NEXT_PUBLIC_BEI_AN
ARG NEXT_PUBLIC_REPO
ARG NEXT_PUBLIC_REPOID
ARG NEXT_PUBLIC_CATEGORY
ARG NEXT_PUBLIC_CATEGORY_ID
ARG NEXT_PUBLIC_MAPPING
ARG NEXT_PUBLIC_TERM
ARG NEXT_PUBLIC_INPUT_POSITION
ARG NEXT_PUBLIC_THEME
ARG NEXT_PUBLIC_LANG
ARG NEXT_PUBLIC_REACTIONS_ENABLED

# 设置为环境变量，使应用能够访问
ENV NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
ENV NEXT_PUBLIC_SITE_NAME=${NEXT_PUBLIC_SITE_NAME}
ENV NEXT_PUBLIC_SITE_DESCRIPTION=${NEXT_PUBLIC_SITE_DESCRIPTION}
ENV NEXT_PUBLIC_AUTHOR_NAME=${NEXT_PUBLIC_AUTHOR_NAME}
ENV NEXT_PUBLIC_TWITTER_USERNAME=${NEXT_PUBLIC_TWITTER_USERNAME}
ENV NEXT_PUBLIC_BAIDU_TONGJI=${NEXT_PUBLIC_BAIDU_TONGJI}
ENV NEXT_PUBLIC_GOOGLE_ID=${NEXT_PUBLIC_GOOGLE_ID}
ENV NEXT_PUBLIC_SEO_GOOGLE_SITE_VERIFICATION=${NEXT_PUBLIC_SEO_GOOGLE_SITE_VERIFICATION}
ENV NEXT_PUBLIC_ADSENSE_GOOGLE_ID=${NEXT_PUBLIC_ADSENSE_GOOGLE_ID}
ENV NEXT_PUBLIC_BEI_AN=${NEXT_PUBLIC_BEI_AN}
ENV NEXT_PUBLIC_REPO=${NEXT_PUBLIC_REPO}
ENV NEXT_PUBLIC_REPOID=${NEXT_PUBLIC_REPOID}
ENV NEXT_PUBLIC_CATEGORY=${NEXT_PUBLIC_CATEGORY}
ENV NEXT_PUBLIC_CATEGORY_ID=${NEXT_PUBLIC_CATEGORY_ID}
ENV NEXT_PUBLIC_MAPPING=${NEXT_PUBLIC_MAPPING}
ENV NEXT_PUBLIC_TERM=${NEXT_PUBLIC_TERM}
ENV NEXT_PUBLIC_INPUT_POSITION=${NEXT_PUBLIC_INPUT_POSITION}
ENV NEXT_PUBLIC_THEME=${NEXT_PUBLIC_THEME}
ENV NEXT_PUBLIC_LANG=${NEXT_PUBLIC_LANG}
ENV NEXT_PUBLIC_REACTIONS_ENABLED=${NEXT_PUBLIC_REACTIONS_ENABLED}

ENV NEXT_TELEMETRY_DISABLED 1

RUN corepack enable && corepack prepare pnpm@8.15.4 --activate && pnpm build

# Production image, copy all the files and run next
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

CMD ["node", "server.js"]